/*
 * mkstring - make a c string out of the first line of the input file.
 *
 * this file is part of the makeutil package:
 *   http://sourceforge.net/projects/makeutil/
 *   http://www.cybermesa.com/~aisa/makeutil/
 *
 * this file is hereby placed in the public domain.
 * aisa0@users.sourceforge.net, aisa@cybermesa.com
 */

static char rcsid[]="$Id: mkstring.c,v 1.3 2004/12/11 18:24:37 aisa0 Exp $";

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

main(argc, argv)
  int argc;
  char *argv[];
{
  FILE *file;
  char line[1024], *fname, *vname;
  size_t n;

  --argc;
  ++argv;

  if(argc!=2) {
    fputs("usage: mkstring filename name\n", stderr);
    exit(EXIT_FAILURE);
  }

  fname=*argv++;
  vname=*argv++;

  if(0==strcmp("-", fname)) {
    file=stdin;
  } else if(NULL==(file=fopen(fname, "r"))) {
    fprintf(stderr, "error: open: %s: ", fname);
    perror("");
    exit(EXIT_FAILURE);
  }
  line[0]='\0';
  if(NULL==fgets(line, sizeof(line)/sizeof(line[0]), file)) {
    if(ferror(file)) {
      fprintf(stderr, "error: read: %s: ", fname);
      perror("");
      exit(EXIT_FAILURE);
    }
  }
  if(EOF==fclose(file)) {
    fprintf(stderr, "error: close: %s: ", fname);
    perror("");
    exit(EXIT_FAILURE);
  }

  fprintf(stdout, "/*\n");
  fprintf(stdout, " * this file is automatically generated\n");
  fprintf(stdout, " */\n");
  fprintf(stdout, "\n");
  fprintf(stdout, "static char rcsid[]=\"%s\";\n", rcsid);
  fprintf(stdout, "\n");

  /* remove newline */
  n=strlen(line);
  if(n && '\n'==line[n-1]) line[--n]='\0';

  fprintf(stdout, "char %s[]=\"%s\";\n", vname, line);
  if(ferror(stdout)) {
    fputs("error: write: -: ", stderr);
    perror("");
    exit(EXIT_FAILURE);
  }
  if(EOF==fclose(stdout)) {
    fprintf(stderr, "error: close: -: ");
    perror("");
    exit(EXIT_FAILURE);
  }

  exit(EXIT_SUCCESS);
}

/*                                                              ..__
 *                                                              `' "
 */
