#!/bin/sh
#
# mksystype - determine the platform description
#
# this file is part of the makeutil package:
#   https://github.com/alanpost/makeutil
#
# this file is hereby placed in the public domain.
# alyn.post@lodockikumazvati.org
#
#
# the platform description has the following format:
#
#   os-version:kern-version:arch:cc-version:ccdesc:pdesc:filename
#

exec 2>/dev/null

cc="`./ccinfo|tr -- '/:[A-Z]' '..[a-z]'`"

if [ x"$cc" = x ]
then
  cc='unknown-'
fi

pdesc="`head -1 conf-pdesc`"

if [ x"$pdesc" = x ]
then
  pdesc='opt:local'
fi

kern="`uname -s|tr -- '-/:[A-Z]' '...[a-z]'`"

if [ x"$kern" = x ]
then
  echo unknown-:unknown-:unknown:$cc:$pdesc:
else
  unamem=`uname -m|tr -- '-/:[A-Z]' '...[a-z]'`
  unamep=`uname -p|tr -- '-/:[A-Z]' '...[a-z]'`
  unamer=`uname -r|tr -- '-/:[A-Z]' '...[a-z]'`

  case $kern in
  linux)
    kernversion=$unamer

    if [ -r /etc/arch-release ]
    then
      os='arch'
      osversion='unknown'
    elif [ -r /etc/cobolt-release ]
    then
      os='cobolt'
      osversion='unknown'
    elif [ -r /etc/debian_version ]
    then
      os='debian'
      osversion='unknown'
    elif [ -r /etc/familiar-version ]
    then
      os='familiar'
      osversion="`sed 's/Familiar v//' < /etc/familiar-version`"
    elif [ -r /etc/gentoo-release ]
    then
      os='gentoo'
      osversion="`sed 's/Gentoo Base System version //' < /etc/gentoo-release`"
    elif [ -l /etc/mandrake-release ]
    then
      os='mandrake'
      osversion='unkonwn'
    elif [ -r /etc/redhat-release ]
    then
      os='redhat'
      osversion="`rpm -q --qf '%{VERSION}' redhat-release|tr -- '-/:[A-Z]' '...[a-z]'`"
    elif [ -r /etc/slackware-version ]
    then
      os='slackware'
      osversion='unknown'
    elif [ -r /etc/SuSE-release ]
    then
      os='suse'
      osversion='unknown'
    else
      os=$kern
      osversion='unknown'
    fi

    arch=$unamem

    case $arch in
    i486|i586|i686)
      arch='i386'
      ;;
    esac
    ;;
  freebsd)
    kernversion="`echo $unamer|sed 's/\.release.*//'`"
    os=$kern
    osversion=$kernversion
    arch=$unamem
    ;;
  bsd.os|openbsd)
    kernversion=$unamer
    os=$kern
    osversion=$kernversion
    arch=$unamem
    ;;
  darwin|sunos)
    kernversion=$unamer
    os=$kern
    osversion=$kernversion
    arch=$unamep
    ;;
  *)
    kernversion=$unamer
    os=$kern
    osversion=$kernversion
    arch="unknown"
    ;;
  esac

  echo $os-$osversion:$kern-$kernversion:$arch:$cc:$pdesc:
fi

#                                                               ..__
#                                                               `' "
